apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        imagePullPolicy: Always
        name: phpmyadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: PMA_ARBITRARY
            value: '1'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myadmin
  name: myadmin
  namespace: demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: myadmin
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo
type: Opaque
data:
  username: cm9vdA==  # root
  password: cGFzc3dvcmQ= #password
---
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-quickstart
  namespace: demo
spec:
  version: "8.0-v1"
  databaseSecret:
    secretName: mysql-secret
  #storageType: Durable
  storageType: Ephemeral
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  #terminationPolicy: DoNotTerminate
  terminationPolicy: WipeOut
